Repository rangle/augury-labs, pull requests merged in 2019-04, with the labels that each got.

#44 Adding ng-add schematics
  README.md
  docs/manual-installation.md
  package.json
  packages/schematics/README.md
  packages/schematics/jest.config.js
  packages/schematics/package.json
  packages/schematics/src/ast/add-script-to-package-json/add-script-to-package-json.ts
  packages/schematics/src/ast/ast-helpers.ts
  packages/schematics/src/collection.json
  packages/schematics/src/rules/add-augury-main.rule.ts
  packages/schematics/src/rules/add-augury-scripts.rule.ts
  packages/schematics/src/rules/add-build-configuration.rule.ts
  packages/schematics/src/rules/add-package-json-dependencies.rule.ts
  packages/schematics/src/rules/install-node-packages.rule.ts
  packages/schematics/src/rules/rule-helpers.ts
  packages/schematics/src/schematics/ng-add/files/main.augury.ts
  packages/schematics/src/schematics/ng-add/index.spec.ts
  packages/schematics/src/schematics/ng-add/index.ts
  packages/schematics/src/schematics/ng-add/schema.json
  packages/schematics/src/types/ng-add.schema.ts
  packages/schematics/src/types/npm-registry-package.ts
  packages/schematics/src/types/npm-script.ts
  packages/schematics/tsconfig.json
  packages/schematics/webpack.config.js
  tslint.json
  yarn.lock
Labels: enhancement

#48 docs: update dev guide
  docs/development-guide.md
Labels: documentation

#51 refactor: update to use typscript project references
  .gitignore
  examples/augury-demo/angular.json
  examples/augury-demo/package.json
  package.json
  packages/core/tsconfig.json
  packages/core/webpack.config.js
  packages/frontend/src/index.html
  packages/frontend/tsconfig.json
  packages/frontend/webpack.config.js
  packages/performance-profiler-plugin/tsconfig.json
  packages/performance-profiler-plugin/webpack.config.js
  packages/schematics/package.json
  packages/schematics/src/ast/add-script-to-package-json/add-script-to-package-json.ts
  packages/schematics/src/index.ts
  packages/schematics/src/rules/add-augury-main.rule.ts
  packages/schematics/tsconfig.json
  packages/schematics/webpack.config.js
  packages/tsconfig.base.json
  packages/tsconfig.json
  packages/unit-tester-plugin/tsconfig.json
  packages/unit-tester-plugin/webpack.config.js
  packages/webpack.config.base.js
  yarn.lock
Labels: internal

#52 refactor: update plugin interfaces & bridge
  .vscode/settings.json
  packages/core/src/augury-window.interface.ts
  packages/core/src/bridge/bridge-connection.interface.ts
  packages/core/src/bridge/bridge-message-type.type.ts
  packages/core/src/bridge/bridge-message.functions.ts
  packages/core/src/bridge/bridge-message.interface.ts
  packages/core/src/bridge/bridge.class.ts
  packages/core/src/bridge/connections/direct-bridge-connection.class.ts
  packages/core/src/bridge/connections/index.ts
  packages/core/src/bridge/index.ts
  packages/core/src/index.ts
  packages/core/src/plugins/augury-plugin-window.interface.ts
  packages/core/src/plugins/bridge/augury-bridge-message.functions.ts
  packages/core/src/plugins/bridge/augury-bridge-message.interface.ts
  packages/core/src/plugins/bridge/augury-bridge-request-type.type.ts
  packages/core/src/plugins/bridge/augury-bridge-request.interface.ts
  packages/core/src/plugins/bridge/augury-bridge.class.ts
  packages/core/src/plugins/bridge/index.ts
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/plugin.class.ts
  packages/core/src/plugins/popup-controller.class.ts
  packages/frontend/src/app/components/change-detection-details/change-detection-details.component.ts
  packages/frontend/src/app/components/instability-details/instability-details.component.ts
  packages/frontend/src/app/services/bridge.service.ts
  packages/frontend/src/app/types/segment/segment.functions.ts
  packages/frontend/src/app/types/segment/segment.interface.ts
  packages/performance-profiler-plugin/src/performance-profiler-controller.class.ts
  packages/performance-profiler-plugin/src/performance-profiler-plugin.class.ts
  packages/tsconfig.json
Labels: refactoring

#56 refactor(frontend): persisting position and size of popup
  packages/core/src/plugins/popup-controller.class.ts
Labels: enhancement

#55 refactor(frontend): Design Updates
  packages/frontend/src/app/app.module.ts
  packages/frontend/src/app/components/header-menu/header-menu.component.html
  packages/frontend/src/app/components/header-menu/header-menu.component.scss
  packages/frontend/src/app/components/header-menu/header-menu.component.ts
  packages/frontend/src/app/components/header/header.component.html
  packages/frontend/src/app/components/index.ts
  packages/frontend/src/app/components/main/main.component.scss
  packages/frontend/src/app/components/segment-details/segment-details.component.scss
  packages/frontend/src/app/components/timeline/timeline.component.scss
Labels: enhancement, ready for review, refactoring

#54 refactor(frontend): turning frontend into Angular Elements
  packages/core/package.json
  packages/core/tsconfig.json
  packages/core/webpack.config.js
  packages/frontend/angular.json
  packages/frontend/ng-package.json
  packages/frontend/package.json
  packages/frontend/src/app/app.module.ts
  packages/frontend/src/app/base-app.module.ts
  packages/frontend/src/app/components/timeline/timeline.component.ts
  packages/frontend/src/app/elements-app.module.ts
  packages/frontend/src/app/types/timeline-graph/timeline-detail-view-graph-boundaries.functions.ts
  packages/frontend/src/app/types/timeline-graph/timeline-detail-view-graph-boundaries.interface.ts
  packages/frontend/src/app/types/timeline-graph/timeline-graphs-boundaries.interface.ts
  packages/frontend/src/app/types/timeline-graph/timeline-overview-graph-boundaries.functions.ts
  packages/frontend/src/app/types/timeline-graph/timeline-overview-graph-boundaries.interface.ts
  packages/frontend/src/main.ts
  packages/frontend/tsconfig.json
  packages/frontend/webpack.config.js
  packages/performance-profiler-plugin/package.json
  packages/performance-profiler-plugin/src/performance-profiler-controller.class.ts
  packages/performance-profiler-plugin/tsconfig.json
  packages/performance-profiler-plugin/webpack.config.js
  packages/unit-tester-plugin/package.json
  packages/unit-tester-plugin/tsconfig.json
  packages/unit-tester-plugin/webpack.config.js
  yarn.lock
Labels: enhancement, ready for review, refactoring
